apiVersion: v1
description: Sonarr is a television show downloading client
name: sonarr
version: 2.0.8
keywords:
  - sonarr
  - usenet
  - bittorrent
home: https://github.com/xmple/charts/tree/master/charts/sonarr
icon: https://avatars1.githubusercontent.com/u/1082903?s=400&v=4
sources:
  - https://hub.docker.com/r/linuxserver/sonarr/
  - https://sonarr.tv/
