apiVersion: v1
description: Bazarr is a companion application to Sonarr and Radarr. It can manage and download subtitles based on your requirements. You define your preferences by TV show or movie and Bazarr takes care of everything for you.
name: bazarr
version: 0.1.7
keywords:
  - bazarr
  - sonarr
  - radarr
  - subtitles
home: https://github.com/xmple/charts/tree/master/charts/bazarr
icon: https://github.com/morpheus65535/bazarr/raw/master/static/logo128.png
sources:
  - https://github.com/morpheus65535/bazarr
  - https://www.bazarr.media/
