apiVersion: v1
description: rtorrent and flood co-located in the same deployment
name: rtorrent
version: 0.1.1
keywords:
  - rtorrent
  - flood
home: https://github.com/xmple/charts/tree/master/charts/rtorrent
icon: https://github.com/jfurrow/flood/blob/master/flood.png?raw=true
sources:
  - https://github.com/linuxserver/docker-rutorrent
  - https://github.com/Flood-UI/flood
