apiVersion: v1
description: NZBGet is a Usenet downloader client
name: nzbget
version: 2.0.12
keywords:
  - nzbget
  - usenet
home: https://github.com/xmple/charts/tree/master/charts/nzbget
icon: https://avatars1.githubusercontent.com/u/3368377?s=400&v=4
sources:
  - https://hub.docker.com/r/linuxserver/nzbget/
  - https://nzbget.net/
