apiVersion: v1
description: qBittorrent is a cross-platform free and open-source BitTorrent client
name: qbittorrent
version: 0.1.3
keywords:
  - qbittorrent
home: https://github.com/xmple/charts/tree/master/charts/qbittorrent
icon: https://cloud.githubusercontent.com/assets/14862437/23586868/89ef2922-01c4-11e7-869c-52aafcece17f.png
sources:
  - https://hub.docker.com/r/linuxserver/qbittorrent/
