apiVersion: v1
description: Radarr is a movie downloading client
name: radarr
version: 2.0.10
keywords:
  - radarr
  - usenet
  - bittorrent
home: https://github.com/xmple/charts/tree/master/charts/radarr
icon: https://avatars3.githubusercontent.com/u/25025331?s=400&v=4
sources:
  - https://hub.docker.com/r/linuxserver/radarr/
  - https://github.com/Radarr/Radarr/
